s=set()
s.add(input('Enter the number:'))
s.add(input('Enter the number:'))
s.add(input('Enter the number:'))
s.add(input('Enter the number:'))
s.add(input('Enter the number:'))
s.add(input('Enter the number:'))
s.add(input('Enter the number:'))
s.add(input('Enter the number:'))
print(s)